[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prodencer"
version = "1.0"
description = "Project charge/spin Densities onto Cubic/tesseral harmonics and space-group Representations."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name="Luca Buiarelli"},
    {name="Seongjoo Jung"},
    {name="Hyeonseo Park"},
    {name="Turan Birol"}
]
license = {text = "CC0"}
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "mplcursors",
    "spglib",
    "spgrep",
    "netCDF4",
]

[project.urls]
homepage = "https://github.com/lucabuia/prodencer"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]